### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by nicolemah99** [acep-uaf/the-arctic-program#105]
- [x] Fix "More" link or remove.
- [x] Fix footer logo links
- [x] Add space under footer logos
- [x] Investigate footer layout when small screen
- [x] Adjust footer logo sizes with css `object-fit`

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Fixed 'More' link, adjusted footer logo links and sizing, added space under footer logos, and improved small screen layout.

You can review changes in this commit: https://github.com/jjyutm4532/acep-uaf-the-arctic-program-105/commit/0058f11909668399fe2cf987a34ede05dba324a7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
