### ISSUE TITLE
/about DoD Relevance/Impact

### ISSUE THREAD

**Issue by dayne** [acep-uaf/the-arctic-program#44]
NSAR Pillars: 1, 2, 3, 4. ARP PAs: 1, 3, 4

.... 

The Alaska RegionalRegional Collaboration for Technology Innovation and Commercialization (ARCTIC) program is an Office of Naval (ONR) funded capacity-building program established in 2017 designed to support the Navy’s needs for public-private partnerships that promote commerce and collaboration between Alaska and the Arctic and Pacific regions, centered on energy systems and resiliency research. The program is designed to help Alaskan organizations and communities develop a thriving innovation ecosystem through energy resiliency research, technology development/deployment, and education by leveraging and building capacity & networks of partners to accelerate the energy transition in Alaska and the North while also building key partnerships between Alaska and the Arctic and Pacific regions. It is intended to directly support the US, DOD, and Navy’s strategic goals for Alaska and the Arctic, and specifically, to build local capacity in Alaska to improve and boost Alaska’s ability to support increased domain awareness and improve the ability for our forces to operate within Alaska and the Arctic region by enhancing the capacity and resilience of the local infrastructure and the connected workforce.  Highlighted in the Navy’s 2021 Blue Arctic strategy as an example of their investment in building public-private partnerships and innovative solutions to help transform operating abilities and regional understanding for Naval forces.

**Comment by nicolemah99** [comment]
Reworded a teeny tiny bit.
---

The Alaska Regional Collaboration for Technology Innovation and Commercialization (ARCTIC) program is an Office of Naval Research (ONR) funded capacity-building program established in 2017, designed to support the Navy’s needs for public-private partnerships that promote commerce and collaboration between Alaska and the Arctic and Pacific regions, centered on energy systems and resiliency research.

The program is designed to help Alaskan organizations and communities develop a thriving innovation ecosystem through energy resiliency research, technology development and deployment, and education. It leverages partnerships and builds capacity across networks to accelerate the energy transition in Alaska and the North, while also fostering key collaborations between Alaska and the Arctic and Pacific regions. 

It is intended to directly support the U.S., Department of Defense (DoD), and Navy’s strategic goals for Alaska and the Arctic. Specifically, it aims to build local capacity in Alaska to improve and boost the state's ability to support increased domain awareness and enhance operational abilities for **military(?)** forces within Alaska and the Arctic region. This is accomplished by enhancing the capacity and resilience of local infrastructure and connected workforce. 

The **ARCTIC** program is highlighted in the Navy’s 2021 *Blue Arctic* strategy as an example of their investment in building public-private partnerships and innovative solutions. These efforts aim to transform operating abilities and regional understanding for Naval forces.
