### ISSUE TITLE
standardize the hero section in all pages

### ISSUE THREAD

**Issue by vlraymond** [acep-uaf/the-arctic-program#64]
3 different styles across 4 pages
better to pick one so the user knows what to expect

home:
![image](https://github.com/user-attachments/assets/f3f6d929-0d13-42e5-ad27-d810acb1f29b)

about:
![image](https://github.com/user-attachments/assets/3b0dc8d6-3929-45a1-be0b-6a149327c6ee)

activities:
![image](https://github.com/user-attachments/assets/2cae5300-72a5-45a7-be29-e48608d80de1)

partners:
![image](https://github.com/user-attachments/assets/67e302d7-9741-4cbe-8a81-2ca3020c10e1)

**Comment by nicolemah99** [comment]
Relates to #95
