### ISSUE TITLE
/activities - hero section text

### ISSUE THREAD

**Issue by vlraymond** [acep-uaf/the-arctic-program#97]
change from:
```ARCTIC’s five foundational activities are designed to drive Alaska’s resilience and innovation economy through strong collaboration with local and state partners. Guided by a cross-cutting Program Management and Support task, these foundational activities demonstrate the program’s commitment to addressing challenges and fostering opportunities through a dynamic and interconnected approach.```

to:
subtitle text: "Driving Alaska's resilience and innovation economy through collaboration"

**Comment by nicolemah99** [comment]
Do you mean like this? Or do You mean right up under the title? That would change the consistent header vibe but happy to do it if that's what you want.

<img width="1221" alt="Screenshot 2024-11-27 at 4 14 58 PM" src="https://github.com/user-attachments/assets/b7334a32-0e8d-46f6-bac5-05062791b196">

**Comment by vlraymond** [comment]
Yes! That
